# Generated by Django 5.2.16 on 2026-08-23 19:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
