# Generated by Django 5.2.16 on 2026-09-17 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stock_reserved',
            field=models.BooleanField(default=True),
        ),
    ]
